### ISSUE TITLE
[Question]  Localization.

### ISSUE THREAD

**Issue by SthanDust** [openrpg/OpenRpg#3]
Localization -- NameLocaleId is a unique ID for the object so it can be localized.  DescriptionLocaleID, is that supposed to be en-gb or something along those lines?  I was a bit confused because you don't mention it in docs.
I would also expand that interface to have a "FriendlyName", for display purposes.  I would also propose a standard for localization, such as ITEM_ARMOR_LEATHER_HELM, or something along those lines.

Just thoughts, I've been playing in the code for two days haha.

**Comment by grofit** [comment]
The LocaleId stuff was originally going to be int based keys like everything else, but it was decided to just go with strings for keys, this way you can just use the `NameLocaleId` directly as a name like "Bobby McBobFace" if you don't care about supporting other languages.

The way its meant to be used though is that you have:

- *NameLocaleId* : The key to get the name string from locale repository/whatever i.e `item-long-sword-name`
- *DescriptionLocaleId* : The key to get the description string from the locale repository/whatever i.e `item-long-sword-description`

You can add more data via variables if you want, but its assumed in almost all use cases you would want to have a name and description on most user facing data objects.

So now we have the notion of the locale keys we then look at the `ILocaleRepository` which contains all the locales for a given code (this has changed a bit recently). So realistically you are only going to have 1 locale loaded in at a given point in time which would be `en-gb` or some other code. However the key thing is the objects with locale data dont know what locale is being used they just contain the key so regardless of what locale the game is using, it just picks out the string for that key.

Here is an [older example of a locale file](https://github.com/openrpg/OpenRpg.Editor/blob/master/src/OpenRpg.Editor.Server/Content/Locales/en-gb.lang.json), these have changed a bit in the latest version of the editor, but are pretty much doing same job, they contain all the locale strings for each locale code.

If you had a scenario where you wanted to load in multiple locales at once you could just have 2 `LocaleDataset` objects loaded and just switch them on the repo when you want to swap languages.

At the moment its all a bit primitive, but almost all localisation on games/websites ends up using a key to indicate the type of locale string, and some database/api that takes the key and provides the text for that locale. This way you write the name/description keys once (and can just use a convention for it if you wanted rather than hand writing them), then just make sure your locale file has them all in.

As you mention though you can just bypass all this and hard code the strings, that's what I do in my mess around projects and when they get bit enough I just move them over to locale keys with locale files. If you wanted some computed data based off them then its probably better to inherit/compose your own class which expresses those bits on top of the base objects.

**Comment by grofit** [comment]
Oh sorry also in terms of convention we don't set a convention for locale codes, its up to the consumer. Internally we use `item-xxx-name` or `class-xxx-description` etc but everyone can use their own naming schemes or conventions. There did used to be classes which auto generated them based off the asset code, but as asset code is no longer 1st class data and optional variable data those classes were removed in favour of consumers just handling it how they want, but if you did want to auto generate them just make an inherited object which has an auto getter using the id or something, or some custom variable like:

```
public string NameLocaleId => $"item-{Id}-name";
// or
public string DescriptionLocaleId => $"item-{Variables.AssetCode()}-description";
```

**Comment by grofit** [comment]
Marking this as closed but feel free to re-open or drop in the discord if you have more questions
